server:
  port: 333
  servlet:
    context-path: /test

spring:
  profiles:
    #dev
    active: dev
  devtools:
    add-properties: false

logging:
  level:
    com:
      exam:
        mapper: 'debug'
    web: debug